name: Fluid Dynamics Calculations Pipeline

on:
  push:
    branches:
      - "**" # Triggers on any branch
  workflow_dispatch:

jobs:
  fluid_dynamics_calculations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13" # Ensure consistent Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest # Explicitly install pytest

    - name: List installed packages (Debugging)
      run: pip list

    # Ensure input file `boundary_conditions.json` exists before execution
    - name: Verify Input File Exists
      run: |
        INPUT_FILE="${GITHUB_WORKSPACE}/data/testing-input-output/boundary_conditions.json"
        if [ ! -f "$INPUT_FILE" ]; then
          echo "❌ Error: Input file boundary_conditions.json is missing at $INPUT_FILE!"
          exit 1
        fi
        echo "✅ Input file boundary_conditions.json found at $INPUT_FILE."

    # Debugging: Print full directory tree before running main.py
    - name: Debugging - List All Files in Repository
      run: ls -R "${GITHUB_WORKSPACE}"
    
    # Run the main CFD simulation script
    - name: Run Fluid Dynamics Calculations
      run: |
        python "${GITHUB_WORKSPACE}/src/main.py"
        echo "✅ Fluid dynamics calculations executed successfully."

    # Ensure output file exists after execution
    - name: Verify Output File Exists
      run: |
        OUTPUT_FILE="${GITHUB_WORKSPACE}/data/testing-input-output/fluid_dynamics_results.json"
        if [ ! -f "$OUTPUT_FILE" ]; then
          echo "❌ Error: Fluid dynamics simulation output file not found at $OUTPUT_FILE!"
          exit 1
        fi
        echo "✅ Output file fluid_dynamics_results.json found at $OUTPUT_FILE."

    - name: Debugging - Show Output File Contents
      run: cat "${GITHUB_WORKSPACE}/data/testing-input-output/fluid_dynamics_results.json"

    # --- Testing Steps (Commented for Now) ---
    # - name: Run unit tests
    #   run: pytest "${GITHUB_WORKSPACE}/tests/test_unit_validation.py" --verbose

    # - name: Run output validation tests
    #   run: |
    #     OUTPUT_FILE="${GITHUB_WORKSPACE}/data/testing-input-output/fluid_dynamics_results.json"
    #     if [ ! -s "$OUTPUT_FILE" ]; then
    #       echo "❌ Error: $OUTPUT_FILE is empty or malformed!"
    #       exit 1
    #     fi
    #     pytest "${GITHUB_WORKSPACE}/tests/test_output_validation.py" --verbose

    # - name: Run integration tests
    #   run: pytest "${GITHUB_WORKSPACE}/tests/test_integration_validation.py" --verbose

    # - name: Run performance tests
    #   run: pytest "${GITHUB_WORKSPACE}/tests/test_performance_testing.py" --verbose

    # --- Commit and Push Updated Simulation Results (If Tests Pass) ---
    - name: Commit and Push Simulation Results JSON
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"

        cd "$GITHUB_WORKSPACE"
        RESULTS_FILE="data/testing-input-output/fluid_dynamics_results.json"

        if [ -s "$RESULTS_FILE" ]; then
          git add "$RESULTS_FILE"
          git status
          
          if git diff --cached --quiet; then
            echo "✅ No changes to commit in $RESULTS_FILE!"
          else
            git commit -m "Auto-update: Added latest fluid dynamics simulation result"
            git push origin HEAD
          fi
        else
          echo "❌ No valid simulation result file detected ($RESULTS_FILE is empty or missing), skipping commit."
        fi
