name: Fluid Dynamics Calculations Pipeline

on:
  push:
    branches:
      - "**" # Triggers on any branch
  workflow_dispatch:

jobs:
  fluid_dynamics_calculations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13" # Ensure consistent Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest # Explicitly install pytest

    - name: List installed packages (Debugging)
      run: pip list

    # Ensure the 'data/testing-input-output' directory exists and contains the boundary_conditions.json
    # This step implicitly handles the working directory by checking the absolute path.
    - name: Verify Input File Exists
      run: |
        # Use GITHUB_WORKSPACE for absolute path
        INPUT_FILE="${GITHUB_WORKSPACE}/data/testing-input-output/boundary_conditions.json"
        if [ ! -f "$INPUT_FILE" ]; then
          echo "❌ Error: Input file boundary_conditions.json is missing at $INPUT_FILE!"
          exit 1
        fi
        echo "✅ Input file boundary_conditions.json found at $INPUT_FILE."

    - name: Run Fluid Dynamics Calculations
      run: |
        # Use GITHUB_WORKSPACE for absolute paths to ensure scripts run correctly
        python "${GITHUB_WORKSPACE}/src/process_fluid_dynamics.py" \
          "${GITHUB_WORKSPACE}/data/testing-input-output/boundary_conditions.json" \
          "${GITHUB_WORKSPACE}/data/testing-input-output/simulation_results.json"
        echo "✅ Fluid dynamics calculations executed successfully."
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    - name: Verify Output File Exists
      run: |
        OUTPUT_FILE="${GITHUB_WORKSPACE}/data/testing-input-output/simulation_results.json"
        if [ ! -f "$OUTPUT_FILE" ]; then
          echo "❌ Error: Fluid dynamics simulation output file not found at $OUTPUT_FILE!"
          exit 1
        fi
        echo "✅ Output file simulation_results.json found at $OUTPUT_FILE."
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    - name: Debugging: Show Output File Contents
      run: cat "${GITHUB_WORKSPACE}/data/testing-input-output/simulation_results.json"
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    # --- Test Steps ---
    - name: Run unit tests
      run: pytest "${GITHUB_WORKSPACE}/tests/test_unit_validation.py" --verbose
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    - name: Run output validation tests
      run: |
        OUTPUT_FILE="${GITHUB_WORKSPACE}/data/testing-input-output/simulation_results.json"
        if [ ! -s "$OUTPUT_FILE" ]; then
          echo "❌ Error: $OUTPUT_FILE is empty or malformed!"
          exit 1
        fi
        pytest "${GITHUB_WORKSPACE}/tests/test_output_validation.py" --verbose
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    - name: Run integration tests
      run: pytest "${GITHUB_WORKSPACE}/tests/test_integration_validation.py" --verbose
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    - name: Run performance tests
      run: pytest "${GITHUB_WORKSPACE}/tests/test_performance_testing.py" --verbose
      # No need for working-directory here if using absolute paths with GITHUB_WORKSPACE

    # --- Commit and Push Updated Simulation Results (Only If Tests Passed) ---
    - name: Commit and Push Simulation Results JSON
      # Ensure Git environment variables are set for commit/push
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"

        # Change to GITHUB_WORKSPACE to ensure git commands run in the root of the repo
        cd "$GITHUB_WORKSPACE"

        # Add simulation result files if they exist and are not empty
        RESULTS_FILE="data/testing-input-output/simulation_results.json"
        if [ -s "$RESULTS_FILE" ]; then # -s checks if file exists and is not empty
          git add "$RESULTS_FILE"
          git status # Show current git status for debugging

          # Check if there are actual changes staged for commit
          if git diff --cached --quiet; then
            echo "✅ No changes to commit in $RESULTS_FILE!"
          else
            git commit -m "Auto-update: Added latest fluid dynamics simulation result"
            # Use --tags and --force-with-lease carefully; usually just 'git push' is enough.
            # Assuming you want to push to the current branch.
            git push origin HEAD # Pushes the current branch to its upstream remote
          fi
        else
          echo "❌ No valid simulation result file detected ($RESULTS_FILE is empty or missing), skipping commit."
        fi
      # No need for working-directory here as we explicitly 'cd' into GITHUB_WORKSPACE
