name: Fluid Dynamics Calculations Pipeline

on:
  push:
    branches:
      - "**"  # Triggers on any branch
  workflow_dispatch:

jobs:
  fluid_dynamics_calculations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Read Input Data
      run: cat data/testing-input-output/boundary_conditions.json

    - name: Run Fluid Dynamics Calculations
      run: |
        python src/process_fluid_dynamics.py data/testing-input-output/boundary_conditions.json

    - name: Verify Output File Exists
      run: |
        if [ -f data/testing-input-output/fluid_flow_parameters.json ]; then
          echo "✅ Fluid dynamics output successfully created."
        else
          echo "❌ Error: Fluid dynamics output file not found!" && exit 1
        fi

    - name: Run Unit and Integration Tests
      run: |
        python -m unittest discover -s tests
      continue-on-error: false  # Fails the workflow if tests fail

    - name: Commit and Push Fluid Dynamics Result to Repository
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"

        # Ensure we are in the correct repo directory
        cd $GITHUB_WORKSPACE

        # Add fluid dynamics result files if they exist
        if ls data/testing-input-output/fluid_flow_parameters.json 1> /dev/null 2>&1; then
          git add data/testing-input-output/fluid_flow_parameters.json
          git status
          
          if git diff --cached --quiet; then
            echo "✅ No changes to commit!"
          else
            git commit -m "Auto-update: Added latest fluid dynamics calculation result"
            git push origin HEAD
          fi
        else
          echo "❌ No fluid dynamics result file detected, skipping commit."
        fi



